// Initial mock data for operations - used when no data exists in localStorage
import type { OperationsTask, Reservation, GuestProfile, InboxThread, DailyPricing, PricingRule, MaintenanceIssue, MarketCompetitor, LocalEvent, MarketMetrics, AutomationRule } from '@/types';

// Sample operations tasks
export const initialOperationsTasks: OperationsTask[] = [
  {
    id: 'ot-001',
    type: 'cleaning',
    propertyId: 'p1',
    status: 'queued',
    priority: 'p0',
    scheduledDate: '2026-04-24',
    scheduledTimeStart: '10:00',
    scheduledTimeEnd: '12:00',
    title: 'Turnover Cleaning - Sunset Vista',
    description: 'Deep clean after 5-night stay. Guest checkout at 11am, next guest checking in at 4pm.',
    checklist: [
      'Strip all linens and wash',
      'Clean all surfaces (kitchen, bathroom, living areas)',
      'Vacuum and mop all floors',
      'Restock amenities (toiletries, coffee, etc.)',
      'Check for damages or maintenance needs',
      'Take completion photos',
    ],
    relatedReservationId: 'res-003',
    nextGuestArrival: '2026-04-24T16:00:00',
    estimatedDuration: 120,
    assigneeName: 'Maria Cleaning Co.',
  },
  {
    id: 'ot-002',
    type: 'cleaning',
    propertyId: 'p2',
    status: 'in_progress',
    priority: 'p1',
    scheduledDate: '2026-04-22',
    scheduledTimeStart: '14:00',
    scheduledTimeEnd: '16:00',
    title: 'Same-Day Turnover - Marina Loft',
    description: 'Quick turnover between guests. Checkout 11am, check-in 4pm.',
    checklist: [
      'Change linens',
      'Clean bathrooms',
      'Kitchen cleanup',
      'Vacuum common areas',
      'Restock supplies',
      'Quick walkthrough',
    ],
    relatedReservationId: 'res-005',
    nextGuestArrival: '2026-04-22T16:00:00',
    estimatedDuration: 90,
    assigneeId: 'cleaner-001',
    assigneeName: 'Sarah Johnson',
    notes: 'Guest left early - started cleaning at 10am',
  },
  {
    id: 'ot-003',
    type: 'maintenance',
    propertyId: 'p1',
    status: 'queued',
    priority: 'p2',
    scheduledDate: '2026-04-25',
    scheduledTimeStart: '09:00',
    scheduledTimeEnd: '10:00',
    title: 'Fix bathroom faucet leak',
    description: 'Guest reported slow drip from bathroom sink faucet. Needs new washer.',
    relatedReservationId: 'res-003',
    estimatedDuration: 60,
    assigneeName: 'Mike\'s Handyman Service',
    notes: 'Parts ordered, arriving Thursday',
  },
  {
    id: 'ot-004',
    type: 'cleaning',
    propertyId: 'p3',
    status: 'completed',
    priority: 'p1',
    scheduledDate: '2026-04-21',
    scheduledTimeStart: '11:00',
    scheduledTimeEnd: '13:00',
    completedAt: '2026-04-21T12:45:00',
    title: 'Post-Checkout Deep Clean - Harbor House',
    description: 'Weekly rental checkout cleaning.',
    checklist: [
      'Full linen service',
      'Deep clean kitchen',
      'Bathroom sanitization',
      'Floor cleaning',
      'Amenity restock',
      'Damage inspection',
    ],
    relatedReservationId: 'res-001',
    nextGuestArrival: '2026-04-22T15:00:00',
    estimatedDuration: 120,
    actualDuration: 105,
    assigneeId: 'cleaner-002',
    assigneeName: 'Clean Sweep Services',
    notes: 'All good - no damages found',
  },
  {
    id: 'ot-005',
    type: 'inspection',
    propertyId: 'p2',
    status: 'queued',
    priority: 'p3',
    scheduledDate: '2026-04-28',
    scheduledTimeStart: '10:00',
    scheduledTimeEnd: '11:00',
    title: 'Monthly property inspection',
    description: 'Routine monthly walkthrough to check for maintenance needs.',
    estimatedDuration: 60,
    notes: 'Check HVAC filters, smoke detectors, and outdoor areas',
  },
];

// Sample reservations (matching the operations tasks)
export const initialReservations: Reservation[] = [
  {
    id: 'res-001',
    propertyId: 'p3',
    guestId: 'guest-001',
    source: 'airbnb',
    status: 'checked_out',
    checkIn: '2026-04-15',
    checkOut: '2026-04-21',
    bookedAt: '2026-03-10T14:30:00',
    nightlyRate: 175,
    totalNights: 6,
    subtotal: 1050,
    cleaningFee: 125,
    serviceFee: 147,
    taxes: 118,
    total: 1440,
    guests: 4,
    adults: 2,
    children: 2,
    confirmationCode: 'ABN-HC8392',
    specialRequests: 'Early check-in if possible',
  },
  {
    id: 'res-002',
    propertyId: 'p1',
    guestId: 'guest-002',
    source: 'booking',
    status: 'checked_in',
    checkIn: '2026-04-19',
    checkOut: '2026-04-24',
    bookedAt: '2026-04-01T09:15:00',
    nightlyRate: 195,
    totalNights: 5,
    subtotal: 975,
    cleaningFee: 150,
    serviceFee: 112,
    taxes: 107,
    total: 1344,
    guests: 2,
    adults: 2,
    confirmationCode: 'BKG-2847391',
  },
  {
    id: 'res-003',
    propertyId: 'p1',
    guestId: 'guest-003',
    source: 'vrbo',
    status: 'upcoming',
    checkIn: '2026-04-24',
    checkOut: '2026-04-28',
    bookedAt: '2026-04-05T16:45:00',
    nightlyRate: 195,
    totalNights: 4,
    subtotal: 780,
    cleaningFee: 150,
    serviceFee: 93,
    taxes: 82,
    total: 1105,
    guests: 3,
    adults: 2,
    children: 1,
    confirmationCode: 'VRBO-18475',
    specialRequests: 'Crib needed for toddler',
  },
  {
    id: 'res-004',
    propertyId: 'p2',
    guestId: 'guest-004',
    source: 'airbnb',
    status: 'checked_out',
    checkIn: '2026-04-18',
    checkOut: '2026-04-22',
    bookedAt: '2026-03-28T11:20:00',
    nightlyRate: 165,
    totalNights: 4,
    subtotal: 660,
    cleaningFee: 100,
    serviceFee: 91,
    taxes: 76,
    total: 927,
    guests: 2,
    adults: 2,
    confirmationCode: 'ABN-ML4721',
  },
  {
    id: 'res-005',
    propertyId: 'p2',
    guestId: 'guest-005',
    source: 'direct',
    status: 'upcoming',
    checkIn: '2026-04-22',
    checkOut: '2026-04-26',
    bookedAt: '2026-04-10T13:00:00',
    nightlyRate: 180,
    totalNights: 4,
    subtotal: 720,
    cleaningFee: 100,
    serviceFee: 0, // No service fee for direct bookings
    taxes: 82,
    total: 902,
    guests: 2,
    adults: 2,
    confirmationCode: 'DIR-20260422',
    notes: 'Repeat guest - VIP treatment',
  },
];

// Sample guests
export const initialGuests: Record<string, GuestProfile> = {
  'guest-001': {
    id: 'guest-001',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@email.com',
    phone: '+1 (555) 123-4567',
    source: 'airbnb',
    rating: 4.9,
    totalTrips: 12,
    totalSpent: 5200,
    verified: true,
    joinDate: '2024-01-15',
    language: 'en',
    timezone: 'America/Los_Angeles',
    flags: ['repeat'],
    lastStayDate: '2026-04-21',
    favoriteProperty: '1',
    preferences: {
      temperature: '72°F',
      checkInTime: 'After 4pm',
      specialRequests: ['Extra towels', 'Work desk needed'],
    },
  },
  'guest-002': {
    id: 'guest-002',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah.w@email.com',
    phone: '+1 (555) 234-5678',
    source: 'booking',
    rating: 5.0,
    totalTrips: 8,
    totalSpent: 3800,
    verified: true,
    joinDate: '2023-11-20',
    language: 'en',
    timezone: 'America/New_York',
    flags: ['vip', 'repeat'],
    lastStayDate: '2026-04-24',
    favoriteProperty: '1',
    notes: 'Excellent guest - always leaves property in great condition',
  },
  'guest-003': {
    id: 'guest-003',
    firstName: 'David',
    lastName: 'Martinez',
    email: 'dmartinez@email.com',
    phone: '+1 (555) 345-6789',
    source: 'vrbo',
    rating: 4.8,
    totalTrips: 5,
    verified: true,
    joinDate: '2025-03-10',
    language: 'en',
    timezone: 'America/Chicago',
    notes: 'Traveling with young family - very respectful guests',
  },
  'guest-004': {
    id: 'guest-004',
    firstName: 'Emily',
    lastName: 'Thompson',
    email: 'emily.t@email.com',
    source: 'airbnb',
    totalTrips: 3,
    verified: false,
    joinDate: '2026-01-05',
    language: 'en',
    timezone: 'America/Denver',
  },
  'guest-005': {
    id: 'guest-005',
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'rjohnson@email.com',
    phone: '+1 (555) 456-7890',
    source: 'direct',
    rating: 5.0,
    totalTrips: 15,
    totalSpent: 8500,
    verified: true,
    joinDate: '2023-06-01',
    language: 'en',
    timezone: 'America/Los_Angeles',
    notes: 'VIP repeat guest - always books direct',
    flags: ['vip', 'repeat'],
    lastStayDate: '2026-04-26',
    favoriteProperty: '1',
    preferences: {
      bedding: 'Extra firm pillows',
      temperature: '68°F',
      checkInTime: 'Flexible',
      specialRequests: ['Quiet location', 'Ground floor preferred'],
    },
  },
};

// Sample inbox threads
export const initialInboxThreads: InboxThread[] = [
  {
    id: 'thread-001',
    guestId: 'guest-003',
    propertyId: 'p1',
    reservationId: 'res-003',
    source: 'vrbo',
    unread: 1,
    lastMessageAt: '2026-04-22T09:30:00',
    urgent: false,
    resolved: false,
    messages: [
      {
        id: 'msg-001',
        threadId: 'thread-001',
        sender: 'host',
        source: 'vrbo',
        text: 'Hi David! Looking forward to hosting you on the 24th. Just confirming - you mentioned needing a crib for your toddler. We have one ready for you!',
        timestamp: '2026-04-21T14:00:00',
        read: true,
      },
      {
        id: 'msg-002',
        threadId: 'thread-001',
        sender: 'guest',
        source: 'vrbo',
        text: 'Perfect, thank you! Also, is there any chance we could check in around 2pm instead of 4pm? Our flight arrives early.',
        timestamp: '2026-04-22T09:30:00',
        read: false,
      },
    ],
  },
  {
    id: 'thread-002',
    guestId: 'guest-002',
    propertyId: 'p1',
    reservationId: 'res-002',
    source: 'booking',
    unread: 0,
    lastMessageAt: '2026-04-20T16:45:00',
    urgent: false,
    resolved: true,
    messages: [
      {
        id: 'msg-003',
        threadId: 'thread-002',
        sender: 'guest',
        source: 'booking',
        text: 'Hi! We just checked in - the property is beautiful! Small issue though - the bathroom faucet is dripping a bit.',
        timestamp: '2026-04-20T16:30:00',
        read: true,
      },
      {
        id: 'msg-004',
        threadId: 'thread-002',
        sender: 'host',
        source: 'booking',
        text: 'Thanks for letting me know, Sarah! I have a handyman scheduled to fix that on Friday. It shouldn\'t interfere with your stay. Let me know if there\'s anything else!',
        timestamp: '2026-04-20T16:45:00',
        read: true,
      },
    ],
  },
];

// Helper function to generate daily pricing for a date range
function generateDailyPricing(
  propertyId: string,
  startDate: Date,
  days: number,
  basePrice: number
): DailyPricing[] {
  const pricing: DailyPricing[] = [];

  for (let i = 0; i < days; i++) {
    const date = new Date(startDate);
    date.setDate(date.getDate() + i);
    const dateStr = date.toISOString().split('T')[0];
    const dayOfWeek = date.getDay();
    const isWeekend = dayOfWeek === 5 || dayOfWeek === 6; // Friday or Saturday

    // Weekend pricing is 20% higher
    const weekendMultiplier = isWeekend ? 1.2 : 1.0;
    const finalPrice = Math.round(basePrice * weekendMultiplier);

    pricing.push({
      date: dateStr,
      propertyId,
      basePrice,
      finalPrice,
      minStay: isWeekend ? 2 : 1,
      strategy: isWeekend ? 'weekend' : 'base',
      strategyLabel: isWeekend ? 'Weekend Rate' : 'Base Rate',
      available: true,
      booked: false,
      blocked: false,
    });
  }

  return pricing;
}

// Sample daily pricing (next 60 days for property 1)
export const initialDailyPricing: DailyPricing[] = generateDailyPricing(
  '1',
  new Date('2026-04-22'),
  60,
  195 // Base price
);

// Sample pricing rules
export const initialPricingRules: PricingRule[] = [
  {
    id: 'rule-001',
    propertyId: '1',
    name: 'Weekend Premium',
    enabled: true,
    priority: 1,
    recurring: 'weekends',
    daysOfWeek: [5, 6], // Friday, Saturday
    priceAdjustment: 20,
    adjustmentType: 'percentage',
    minStay: 2,
    strategy: 'weekend',
    description: '20% premium on Friday and Saturday nights with 2-night minimum',
  },
  {
    id: 'rule-002',
    propertyId: '1',
    name: 'SXSW Festival (March 2027)',
    enabled: true,
    priority: 0, // Highest priority
    startDate: '2027-03-11',
    endDate: '2027-03-20',
    priceAdjustment: 150,
    adjustmentType: 'percentage',
    minStay: 3,
    strategy: 'event',
    description: 'SXSW festival pricing - 150% increase with 3-night minimum',
  },
  {
    id: 'rule-003',
    propertyId: '1',
    name: 'Last Minute (7 days out)',
    enabled: true,
    priority: 2,
    priceAdjustment: -15,
    adjustmentType: 'percentage',
    strategy: 'last_minute',
    description: '15% discount for bookings within 7 days to fill gaps',
  },
  {
    id: 'rule-004',
    propertyId: '1',
    name: 'Summer Season',
    enabled: true,
    priority: 3,
    startDate: '2026-06-01',
    endDate: '2026-08-31',
    priceAdjustment: 25,
    adjustmentType: 'percentage',
    minStay: 3,
    strategy: 'seasonal',
    description: 'Summer high season - 25% increase with 3-night minimum',
  },
  {
    id: 'rule-005',
    propertyId: '1',
    name: 'Formula 1 Austin (October)',
    enabled: true,
    priority: 0,
    startDate: '2026-10-22',
    endDate: '2026-10-25',
    priceAdjustment: 200,
    adjustmentType: 'percentage',
    minStay: 3,
    maxStay: 7,
    strategy: 'event',
    description: 'F1 US Grand Prix - 200% increase with 3-night minimum',
  },
];

// Sample maintenance issues
export const initialMaintenanceIssues: MaintenanceIssue[] = [
  {
    id: 'issue-001',
    propertyId: '1',
    title: 'Bathroom faucet dripping',
    description: 'Guest reported slow drip from master bathroom sink faucet. Appears to need new washer or cartridge replacement.',
    priority: 'high',
    status: 'assigned',
    source: 'guest',
    reportedBy: 'Sarah Williams',
    reportedAt: '2026-04-20T16:30:00',
    guestId: 'guest-002',
    reservationId: 'res-002',
    assignedTo: "Mike's Handyman Service",
    assignedAt: '2026-04-20T17:00:00',
    estimatedCost: 75,
    category: 'plumbing',
    tags: ['urgent', 'guest-reported'],
    notes: 'Parts ordered, arriving Thursday morning. Scheduled repair for Friday 9am.',
  },
  {
    id: 'issue-002',
    propertyId: '1',
    title: 'HVAC filter replacement needed',
    description: 'Preventive maintenance - HVAC filters are due for replacement. Last changed 3 months ago.',
    priority: 'medium',
    status: 'reported',
    source: 'preventive',
    reportedBy: 'System',
    reportedAt: '2026-04-21T08:00:00',
    estimatedCost: 40,
    category: 'hvac',
    tags: ['preventive', 'routine'],
    notes: 'Schedule with regular cleaning crew or dedicated HVAC tech.',
  },
  {
    id: 'issue-003',
    propertyId: '1',
    title: 'Dishwasher making loud noise',
    description: 'Dishwasher is making grinding/rattling noise during wash cycle. May be debris in pump or failing motor.',
    priority: 'urgent',
    status: 'in_progress',
    source: 'inspection',
    reportedBy: 'Cleaning Staff',
    reportedAt: '2026-04-21T12:45:00',
    assignedTo: 'Appliance Repair Pro',
    assignedAt: '2026-04-21T13:30:00',
    estimatedCost: 150,
    actualCost: 125,
    category: 'appliance',
    tags: ['urgent', 'next-guest-impact'],
    notes: 'Tech on-site now. Found plastic utensil in pump. Removed and tested. Working normally.',
  },
  {
    id: 'issue-004',
    propertyId: '1',
    title: 'Front door lock sticking',
    description: 'Guest had difficulty unlocking front door with smart lock code. Lock mechanism appears to be sticking.',
    priority: 'high',
    status: 'resolved',
    source: 'guest',
    reportedBy: 'Michael Chen',
    reportedAt: '2026-04-15T20:15:00',
    guestId: 'guest-001',
    assignedTo: 'Lock & Key Solutions',
    assignedAt: '2026-04-16T09:00:00',
    resolvedAt: '2026-04-16T11:30:00',
    resolution: 'Cleaned and lubricated lock mechanism. Tested entry codes - all working smoothly. Also replaced batteries as preventive measure.',
    estimatedCost: 100,
    actualCost: 85,
    category: 'other',
    tags: ['guest-access', 'resolved'],
  },
  {
    id: 'issue-005',
    propertyId: '1',
    title: 'Smoke detector chirping',
    description: 'Low battery warning on smoke detector in master bedroom.',
    priority: 'high',
    status: 'resolved',
    source: 'guest',
    reportedBy: 'David Martinez',
    reportedAt: '2026-04-22T22:00:00',
    guestId: 'guest-003',
    assignedTo: 'Self-Service (Owner)',
    assignedAt: '2026-04-22T22:15:00',
    resolvedAt: '2026-04-22T22:30:00',
    closedAt: '2026-04-23T08:00:00',
    resolution: 'Replaced 9V battery. Tested detector - functioning properly.',
    estimatedCost: 0,
    actualCost: 5,
    category: 'other',
    tags: ['quick-fix', 'safety'],
    notes: 'Added reminder to check all smoke detector batteries monthly.',
  },
  {
    id: 'issue-006',
    propertyId: '1',
    title: 'Patio furniture needs cleaning',
    description: 'Outdoor patio furniture has accumulated pollen and dirt. Needs deep cleaning before next guest.',
    priority: 'low',
    status: 'reported',
    source: 'inspection',
    reportedBy: 'Cleaning Staff',
    reportedAt: '2026-04-23T14:00:00',
    estimatedCost: 50,
    category: 'cosmetic',
    tags: ['outdoor', 'low-priority'],
    notes: 'Can be done during next turnover cleaning.',
  },
  {
    id: 'issue-007',
    propertyId: '1',
    title: 'WiFi router needs reset',
    description: 'Guest reported slow internet speeds. Router may need power cycle or firmware update.',
    priority: 'medium',
    status: 'resolved',
    source: 'guest',
    reportedBy: 'Emily Thompson',
    reportedAt: '2026-04-18T15:00:00',
    guestId: 'guest-004',
    reservationId: 'res-004',
    assignedTo: 'Self-Service (Remote)',
    assignedAt: '2026-04-18T15:10:00',
    resolvedAt: '2026-04-18T15:25:00',
    resolution: 'Remotely rebooted router via admin panel. Speed test confirmed normal speeds restored. Advised guest to restart device connections.',
    estimatedCost: 0,
    actualCost: 0,
    category: 'other',
    tags: ['wifi', 'remote-fix'],
  },
];

// =====================================================
// MARKET INTELLIGENCE DATA
// =====================================================

export const initialMarketCompetitors: MarketCompetitor[] = [
  {
    id: 'comp-001',
    name: 'Beachfront Paradise 2BR',
    propertyType: '2BR Condo',
    neighborhood: 'Marina District',
    beds: 2,
    baths: 2,
    sleeps: 6,
    currentPrice: 195,
    priceHistory: [
      { date: '2026-04-01', price: 185 },
      { date: '2026-04-08', price: 190 },
      { date: '2026-04-15', price: 195 },
      { date: '2026-04-22', price: 195 },
    ],
    rating: 4.8,
    reviewCount: 147,
    estimatedOccupancy: 78,
    airbnbUrl: 'https://airbnb.com/rooms/12345',
    distanceFromP1: 0.3,
    distanceFromP2: 0.2,
    distanceFromP3: 1.2,
    lastUpdated: '2026-04-23T08:00:00',
    notes: 'Direct competitor. Similar amenities, slightly lower price.',
  },
  {
    id: 'comp-002',
    name: 'Luxury Marina View 3BR',
    propertyType: '3BR House',
    neighborhood: 'Marina District',
    beds: 3,
    baths: 2.5,
    sleeps: 8,
    currentPrice: 275,
    priceHistory: [
      { date: '2026-04-01', price: 265 },
      { date: '2026-04-08', price: 270 },
      { date: '2026-04-15', price: 275 },
      { date: '2026-04-22', price: 280 },
    ],
    rating: 4.9,
    reviewCount: 89,
    estimatedOccupancy: 85,
    airbnbUrl: 'https://airbnb.com/rooms/23456',
    vrboUrl: 'https://vrbo.com/3456789',
    distanceFromP1: 0.4,
    distanceFromP2: 0.5,
    distanceFromP3: 0.8,
    lastUpdated: '2026-04-23T08:00:00',
    notes: 'Higher-end competitor. Trending up in pricing.',
  },
  {
    id: 'comp-003',
    name: 'Downtown Artist Loft',
    propertyType: '1BR Loft',
    neighborhood: 'Downtown Arts District',
    beds: 1,
    baths: 1,
    sleeps: 2,
    currentPrice: 135,
    priceHistory: [
      { date: '2026-04-01', price: 140 },
      { date: '2026-04-08', price: 138 },
      { date: '2026-04-15', price: 135 },
      { date: '2026-04-22', price: 135 },
    ],
    rating: 4.6,
    reviewCount: 203,
    estimatedOccupancy: 72,
    airbnbUrl: 'https://airbnb.com/rooms/34567',
    bookingUrl: 'https://booking.com/hotel/us/artist-loft',
    distanceFromP1: 2.1,
    distanceFromP2: 0.4,
    distanceFromP3: 1.8,
    lastUpdated: '2026-04-23T08:00:00',
    notes: 'Different market segment but same neighborhood as P2.',
  },
  {
    id: 'comp-004',
    name: 'Sunset Hills Retreat',
    propertyType: '2BR House',
    neighborhood: 'Sunset Hills',
    beds: 2,
    baths: 1,
    sleeps: 4,
    currentPrice: 165,
    priceHistory: [
      { date: '2026-04-01', price: 160 },
      { date: '2026-04-08', price: 162 },
      { date: '2026-04-15', price: 165 },
      { date: '2026-04-22', price: 165 },
    ],
    rating: 4.7,
    reviewCount: 124,
    estimatedOccupancy: 68,
    vrboUrl: 'https://vrbo.com/4567890',
    distanceFromP1: 3.5,
    distanceFromP2: 3.8,
    distanceFromP3: 0.3,
    lastUpdated: '2026-04-23T08:00:00',
    notes: 'Neighborhood competitor for P3. Lower occupancy.',
  },
  {
    id: 'comp-005',
    name: 'Modern Marina Studio',
    propertyType: 'Studio',
    neighborhood: 'Marina District',
    beds: 1,
    baths: 1,
    sleeps: 2,
    currentPrice: 115,
    priceHistory: [
      { date: '2026-04-01', price: 110 },
      { date: '2026-04-08', price: 112 },
      { date: '2026-04-15', price: 115 },
      { date: '2026-04-22', price: 118 },
    ],
    rating: 4.5,
    reviewCount: 276,
    estimatedOccupancy: 82,
    airbnbUrl: 'https://airbnb.com/rooms/45678',
    bookingUrl: 'https://booking.com/hotel/us/modern-marina',
    distanceFromP1: 0.6,
    distanceFromP2: 0.5,
    distanceFromP3: 1.5,
    lastUpdated: '2026-04-23T08:00:00',
    notes: 'Budget option in same area. High occupancy, rising prices.',
  },
];

export const initialLocalEvents: LocalEvent[] = [
  {
    id: 'event-001',
    name: 'Marina Music Festival',
    startDate: '2026-05-15',
    endDate: '2026-05-17',
    category: 'festival',
    impact: 'high',
    expectedVisitors: 15000,
    venue: 'Marina Waterfront Park',
    description: '3-day music festival featuring local and international artists. Expect high demand for waterfront properties.',
    suggestedPriceIncrease: 35,
    suggestedMinStay: 3,
    url: 'https://marinamusicfest.com',
    notes: 'Book early. Consider 3-night minimum for all properties.',
  },
  {
    id: 'event-002',
    name: 'Tech Conference 2026',
    startDate: '2026-06-03',
    endDate: '2026-06-05',
    category: 'conference',
    impact: 'medium',
    expectedVisitors: 5000,
    venue: 'Downtown Convention Center',
    description: 'Annual technology conference. Good for midweek bookings.',
    suggestedPriceIncrease: 20,
    suggestedMinStay: 2,
    url: 'https://techconf2026.com',
    notes: 'Attendees typically book Sunday-Friday.',
  },
  {
    id: 'event-003',
    name: 'Memorial Day Weekend',
    startDate: '2026-05-23',
    endDate: '2026-05-25',
    category: 'holiday',
    impact: 'extreme',
    expectedVisitors: 50000,
    venue: 'Citywide',
    description: 'Major holiday weekend. Peak demand across all neighborhoods.',
    suggestedPriceIncrease: 50,
    suggestedMinStay: 3,
    notes: 'Block calendar early. Expect strong demand 2-3 months out.',
  },
  {
    id: 'event-004',
    name: 'Food & Wine Festival',
    startDate: '2026-04-26',
    endDate: '2026-04-27',
    category: 'festival',
    impact: 'medium',
    expectedVisitors: 8000,
    venue: 'Downtown Arts District',
    description: 'Weekend food festival with wine tastings and chef demonstrations.',
    suggestedPriceIncrease: 25,
    suggestedMinStay: 2,
    url: 'https://foodwinefest.com',
    notes: 'Primarily impacts Downtown properties (P2).',
  },
  {
    id: 'event-005',
    name: 'Marathon & 5K Run',
    startDate: '2026-05-10',
    endDate: '2026-05-10',
    category: 'sports',
    impact: 'low',
    expectedVisitors: 3000,
    venue: 'Marina Waterfront (Start/Finish)',
    description: 'Annual charity marathon. Light impact on bookings but some street closures.',
    suggestedPriceIncrease: 10,
    notes: 'Inform guests of early morning street closures (6am-10am).',
  },
  {
    id: 'event-006',
    name: 'Independence Day Fireworks',
    startDate: '2026-07-04',
    endDate: '2026-07-04',
    category: 'holiday',
    impact: 'high',
    expectedVisitors: 30000,
    venue: 'Marina Waterfront',
    description: 'Major fireworks display at the marina. Very high demand for waterfront views.',
    suggestedPriceIncrease: 60,
    suggestedMinStay: 2,
    notes: 'P1 and P2 have excellent fireworks views. Premium pricing justified.',
  },
];

export const initialMarketMetrics: MarketMetrics[] = [
  {
    date: '2026-04-23',
    neighborhoodOccupancy: 74,
    cityOccupancy: 68,
    avgDailyRate: 185,
    avgMinStay: 2.1,
    demandIndex: 72,
    competitorCount: 147,
    newListings: 8,
    occupancyTrend: 'up',
    priceTrend: 'stable',
    demandTrend: 'up',
  },
  {
    date: '2026-04-16',
    neighborhoodOccupancy: 71,
    cityOccupancy: 66,
    avgDailyRate: 183,
    avgMinStay: 2.2,
    demandIndex: 68,
    competitorCount: 145,
    newListings: 12,
    occupancyTrend: 'stable',
    priceTrend: 'up',
    demandTrend: 'stable',
  },
  {
    date: '2026-04-09',
    neighborhoodOccupancy: 70,
    cityOccupancy: 65,
    avgDailyRate: 180,
    avgMinStay: 2.3,
    demandIndex: 65,
    competitorCount: 143,
    newListings: 5,
    occupancyTrend: 'stable',
    priceTrend: 'stable',
    demandTrend: 'stable',
  },
];

// =====================================================
// AUTOMATION RULES
// =====================================================

export const initialAutomationRules: AutomationRule[] = [
  {
    id: 'auto-001',
    name: 'Auto-Create Turnover Cleaning Task',
    description: 'Automatically create a cleaning task when a guest checks out',
    enabled: true,
    trigger: 'reservation_checkout',
    actions: [
      {
        type: 'create_task',
        params: {
          taskType: 'cleaning',
          title: 'Turnover Cleaning',
          priority: 'p1',
          scheduledHoursAfter: 2,
        },
      },
    ],
    createdAt: '2026-04-01T00:00:00',
    triggerCount: 47,
    lastTriggered: '2026-04-22T11:00:00',
  },
  {
    id: 'auto-002',
    name: 'Event-Based Price Increase',
    description: 'Raise prices by 30% when major events are 7 days away',
    enabled: true,
    trigger: 'event_upcoming',
    conditions: [
      {
        field: 'impact',
        operator: 'equals',
        value: 'extreme',
      },
      {
        field: 'daysUntil',
        operator: 'equals',
        value: 7,
      },
    ],
    actions: [
      {
        type: 'adjust_price',
        params: {
          adjustmentType: 'percentage',
          amount: 30,
          durationDays: 3,
        },
      },
      {
        type: 'update_min_stay',
        params: {
          minStay: 3,
        },
      },
      {
        type: 'send_notification',
        params: {
          title: 'Auto Price Adjustment',
          message: 'Prices increased for upcoming major event',
        },
      },
    ],
    createdAt: '2026-03-15T00:00:00',
    triggerCount: 3,
    lastTriggered: '2026-04-16T00:00:00',
    maxTriggersPerDay: 5,
  },
  {
    id: 'auto-003',
    name: 'Urgent Issue Alert',
    description: 'Send immediate notification when urgent maintenance issue is reported',
    enabled: true,
    trigger: 'issue_urgent',
    actions: [
      {
        type: 'send_notification',
        params: {
          title: 'Urgent Maintenance Issue',
          message: 'Immediate attention required',
          priority: 'high',
        },
      },
    ],
    createdAt: '2026-02-01T00:00:00',
    triggerCount: 12,
    lastTriggered: '2026-04-20T18:30:00',
  },
  {
    id: 'auto-004',
    name: 'Check-In Reminder Task',
    description: 'Create property inspection task 2 hours before guest check-in',
    enabled: true,
    trigger: 'reservation_checkin',
    actions: [
      {
        type: 'create_task',
        params: {
          taskType: 'inspection',
          title: 'Pre-Check-In Inspection',
          priority: 'p1',
          scheduledHoursBefore: 2,
        },
      },
    ],
    createdAt: '2026-03-01T00:00:00',
    triggerCount: 35,
    lastTriggered: '2026-04-21T14:00:00',
  },
  {
    id: 'auto-005',
    name: 'Competitor Price Match',
    description: 'Alert when competitors drop prices significantly below ours',
    enabled: false,
    trigger: 'price_competitor',
    conditions: [
      {
        field: 'priceDifferencePercent',
        operator: 'greater_than',
        value: 15,
      },
    ],
    actions: [
      {
        type: 'send_notification',
        params: {
          title: 'Competitor Price Alert',
          message: 'Competitor pricing is significantly lower',
        },
      },
    ],
    createdAt: '2026-04-10T00:00:00',
    triggerCount: 0,
    cooldownMinutes: 720, // 12 hours
  },
  {
    id: 'auto-006',
    name: 'Guest Welcome Message',
    description: 'Send automated welcome message on check-in day',
    enabled: true,
    trigger: 'reservation_checkin',
    conditions: [
      {
        field: 'hoursUntil',
        operator: 'less_than',
        value: 4,
      },
    ],
    actions: [
      {
        type: 'send_message',
        params: {
          template: 'welcome',
          includeCheckInInstructions: true,
          includeWifiCredentials: true,
        },
      },
    ],
    createdAt: '2026-02-15T00:00:00',
    triggerCount: 42,
    lastTriggered: '2026-04-22T12:00:00',
  },
];
