import type { Task, ChecklistItem } from '@/types';
import { documentationData } from '@/data/documents';

/**
 * Generate smart checklist items based on task content
 */
export function generateChecklistItems(task: Task): ChecklistItem[] {
  const taskLower = task.task.toLowerCase();
  const categoryLower = task.category.toLowerCase();
  const combined = `${taskLower} ${categoryLower}`;

  const items: string[] = [];

  // Permit/License tasks
  if (combined.includes('permit') || combined.includes('license') || combined.includes('registration')) {
    items.push('Application filed', 'Approval received', 'Copy uploaded to documents', 'Expiry date noted');
  }
  // Budget/Financial tasks
  else if (combined.includes('budget') || combined.includes('cost') || combined.includes('pricing') || combined.includes('revenue')) {
    items.push('Budget approved', 'Line items documented', 'Tracked in spreadsheet', 'Variance monitored');
  }
  // Photo/Media tasks
  else if (combined.includes('photo') || combined.includes('video') || combined.includes('media') || combined.includes('image')) {
    items.push('Content captured', 'Edited/processed', 'Uploaded to gallery', 'Tagged and organized');
  }
  // Installation/Setup tasks
  else if (combined.includes('install') || combined.includes('setup') || combined.includes('deploy')) {
    items.push('Parts/materials received', 'Installation completed', 'Tested and verified working', 'Warranty/manual filed');
  }
  // Design tasks
  else if (combined.includes('design') || combined.includes('layout') || combined.includes('floorplan')) {
    items.push('Design concept approved', 'Specifications documented', 'Measurements verified', 'Final design signed off');
  }
  // Inspection/Audit tasks
  else if (combined.includes('inspect') || combined.includes('audit') || combined.includes('review')) {
    items.push('Inspection scheduled', 'Issues identified and documented', 'Corrections completed', 'Final approval obtained');
  }
  // Documentation tasks
  else if (combined.includes('document') || combined.includes('manual') || combined.includes('guide')) {
    items.push('Content drafted', 'Reviewed for accuracy', 'Published/distributed', 'Stakeholders notified');
  }
  // Contract/Legal tasks
  else if (combined.includes('contract') || combined.includes('agreement') || combined.includes('legal')) {
    items.push('Terms negotiated', 'Contract reviewed', 'Signed by all parties', 'Copy filed and backed up');
  }
  // Research/Analysis tasks
  else if (combined.includes('research') || combined.includes('analyze') || combined.includes('evaluate')) {
    items.push('Data collected', 'Analysis completed', 'Findings documented', 'Recommendations created');
  }
  // Vendor/Service tasks
  else if (combined.includes('vendor') || combined.includes('supplier') || combined.includes('contractor')) {
    items.push('Vendor selected', 'Terms agreed', 'Service delivered', 'Quality verified');
  }
  // Generic fallback
  else {
    items.push('Planning completed', 'Execution verified', 'Documentation updated', 'Quality checked');
  }

  // Convert to ChecklistItem objects
  return items.map((text, index) => ({
    id: `auto-${Date.now()}-${index}`,
    text,
    completed: false,
    createdAt: new Date().toISOString(),
    isAutoGenerated: true,
  }));
}

/**
 * Suggest related documents based on task section/category/keywords
 */
export function suggestRelatedDocuments(task: Task): Array<{ id: string; name: string; relevance: number }> {
  const suggestions: Array<{ id: string; name: string; relevance: number }> = [];

  documentationData.forEach(doc => {
    let relevance = 0;

    // Exact section match (high relevance)
    if (doc.section === task.section) {
      relevance += 50;
    }

    // Same timing (medium relevance)
    if (doc.timing === task.timing) {
      relevance += 20;
    }

    // Keyword matching in artifact name and task title
    const docLower = doc.artifact.toLowerCase();
    const taskLower = task.task.toLowerCase();
    const categoryLower = task.category.toLowerCase();

    // Extract keywords (simple word matching)
    const docWords = docLower.split(/\s+/);
    const taskWords = [...taskLower.split(/\s+/), ...categoryLower.split(/\s+/)];

    docWords.forEach(docWord => {
      if (docWord.length > 3 && taskWords.some(tw => tw.includes(docWord) || docWord.includes(tw))) {
        relevance += 10;
      }
    });

    // Type-specific matching
    if (
      (taskLower.includes('budget') && docLower.includes('budget')) ||
      (taskLower.includes('photo') && docLower.includes('photo')) ||
      (taskLower.includes('permit') && docLower.includes('permit')) ||
      (taskLower.includes('manual') && docLower.includes('manual')) ||
      (taskLower.includes('contract') && docLower.includes('contract')) ||
      (taskLower.includes('insurance') && docLower.includes('insurance'))
    ) {
      relevance += 30;
    }

    if (relevance > 20) {
      suggestions.push({
        id: doc.id,
        name: doc.artifact,
        relevance,
      });
    }
  });

  // Sort by relevance and return top 5
  return suggestions
    .sort((a, b) => b.relevance - a.relevance)
    .slice(0, 5);
}

/**
 * Create activity log entry
 */
export function createActivityEntry(action: string, details?: string) {
  return {
    id: crypto.randomUUID(),
    action,
    timestamp: new Date().toISOString(),
    details,
  };
}
