'use client';

import { useState, useMemo } from 'react';
import { useApp } from '@/lib/context';
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import type { Task, ChecklistItem, AttachedFile, TaskActivityEntry } from '@/types';
import { generateChecklistItems, suggestRelatedDocuments, createActivityEntry } from '@/lib/task-suggestions';
import { documentationData } from '@/data/documents';
import Link from 'next/link';

interface TaskDetailDrawerProps {
  task: Task | null;
  isOpen: boolean;
  onClose: () => void;
}

type TabType = 'checklist' | 'documents' | 'history';

export function TaskDetailDrawer({ task, isOpen, onClose }: TaskDetailDrawerProps) {
  const { 
    state, 
    toggleTask, 
    setTaskStatus, 
    setTaskNote, 
    togglePin,
    addChecklistItem,
    toggleChecklistItem,
    removeChecklistItem,
    generateChecklist,
    linkDocument,
    unlinkDocument,
    logActivity,
  } = useApp();
  const [activeTab, setActiveTab] = useState<TabType>('checklist');
  const [newChecklistItem, setNewChecklistItem] = useState('');
  const [noteText, setNoteText] = useState('');

  if (!task) return null;

  const meta = state.taskMeta[task.id] || {};
  const isCompleted = state.completedIds.includes(task.id);
  const isPinned = state.pinnedIds.includes(task.id);
  const status = meta.status || 'default';

  // Initialize checklist if empty
  const checklistItems = meta.checklistItems || [];
  const linkedDocuments = meta.linkedDocuments || [];
  const attachedFiles = meta.attachedFiles || [];
  const activityLog = meta.activityLog || [];

  // Suggested documents
  const suggestedDocs = useMemo(() => {
    return suggestRelatedDocuments(task);
  }, [task]);

  // Completion stats
  const completedChecklist = checklistItems.filter(item => item.completed).length;
  const totalChecklist = checklistItems.length;
  const isVerified = meta.isVerifiedComplete || false;

  // Handlers
  const handleGenerateChecklist = () => {
    const generated = generateChecklistItems(task);
    generateChecklist(task.id, generated);
    logActivity(task.id, 'Generated completion checklist', `${generated.length} items added`);
  };

  const handleToggleChecklistItem = (itemId: string) => {
    toggleChecklistItem(task.id, itemId);
  };

  const handleAddChecklistItem = () => {
    if (!newChecklistItem.trim()) return;
    
    const newItem: ChecklistItem = {
      id: crypto.randomUUID(),
      text: newChecklistItem,
      completed: false,
      createdAt: new Date().toISOString(),
      isAutoGenerated: false,
    };
    
    addChecklistItem(task.id, newItem);
    logActivity(task.id, 'Added checklist item', newItem.text);
    setNewChecklistItem('');
  };

  const handleRemoveChecklistItem = (itemId: string) => {
    const item = checklistItems.find(i => i.id === itemId);
    removeChecklistItem(task.id, itemId);
    if (item) {
      logActivity(task.id, 'Removed checklist item', item.text);
    }
  };

  const handleLinkDocument = (docId: string) => {
    linkDocument(task.id, docId);
    const doc = documentationData.find(d => d.id === docId);
    if (doc) {
      logActivity(task.id, 'Linked document', doc.artifact);
    }
  };

  const handleUnlinkDocument = (docId: string) => {
    const doc = documentationData.find(d => d.id === docId);
    unlinkDocument(task.id, docId);
    if (doc) {
      logActivity(task.id, 'Unlinked document', doc.artifact);
    }
  };

  const handleSaveNote = () => {
    if (noteText.trim()) {
      setTaskNote(task.id, noteText);
      logActivity(task.id, 'Updated notes');
    }
  };

  const handleMarkComplete = () => {
    toggleTask(task.id);
    const wasCompleted = isCompleted;
    logActivity(task.id, wasCompleted ? 'Marked incomplete' : 'Marked complete');
  };

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/60 z-40 backdrop-blur-sm"
          onClick={onClose}
        />
      )}

      {/* Drawer */}
      <div
        className={cn(
          'fixed top-0 right-0 h-full w-full sm:w-[600px] bg-zinc-950 border-l border-zinc-800 z-50',
          'transform transition-transform duration-300 ease-out',
          'overflow-y-auto',
          isOpen ? 'translate-x-0' : 'translate-x-full'
        )}
      >
        {/* Header */}
        <div className="sticky top-0 z-10 bg-zinc-950 border-b border-zinc-800 p-4">
          <div className="flex items-start justify-between mb-3">
            <button
              onClick={onClose}
              className="p-2 hover:bg-zinc-800 rounded-lg transition-colors text-zinc-400 hover:text-white"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>

            <div className="flex gap-2">
              <Button
                variant={isPinned ? 'primary' : 'ghost'}
                size="sm"
                onClick={() => togglePin(task.id)}
              >
                {isPinned ? '📌 Pinned' : 'Pin'}
              </Button>
              <Button
                variant={(status === 'blocked' ? 'danger' : 'ghost') as 'danger' | 'ghost'}
                size="sm"
                onClick={() => setTaskStatus(task.id, status === 'blocked' ? 'default' : 'blocked')}
              >
                {status === 'blocked' ? 'Blocked' : 'Block'}
              </Button>
            </div>
          </div>

          <h2 className="text-xl font-display font-bold text-white mb-1">
            {task.task}
            {isVerified && <span className="ml-2 text-emerald-400">✅</span>}
          </h2>
          <p className="text-sm text-zinc-500">
            {task.section} › {task.category}
          </p>
        </div>

        {/* Tab Navigation */}
        <div className="border-b border-zinc-800 px-4">
          <div className="flex gap-1">
            {[
              { id: 'checklist' as TabType, label: 'Checklist', count: totalChecklist > 0 ? `${completedChecklist}/${totalChecklist}` : null },
              { id: 'documents' as TabType, label: 'Documents', count: linkedDocuments.length + attachedFiles.length || null },
              { id: 'history' as TabType, label: 'Activity', count: null },
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={cn(
                  'px-4 py-3 text-sm font-medium transition-colors border-b-2',
                  activeTab === tab.id
                    ? 'text-blue-400 border-blue-400'
                    : 'text-zinc-500 border-transparent hover:text-zinc-300'
                )}
              >
                {tab.label}
                {tab.count && (
                  <span className="ml-2 text-xs bg-zinc-800 px-1.5 py-0.5 rounded">
                    {tab.count}
                  </span>
                )}
              </button>
            ))}
          </div>
        </div>

        {/* Tab Content */}
        <div className="p-4 space-y-6">
          {/* CHECKLIST TAB */}
          {activeTab === 'checklist' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-zinc-300">Completion Checklist</h3>
                {checklistItems.length === 0 && (
                  <Button size="sm" variant="secondary" onClick={handleGenerateChecklist}>
                    Generate Smart Checklist
                  </Button>
                )}
              </div>

              {/* Checklist items */}
              <div className="space-y-2">
                {checklistItems.length === 0 ? (
                  <div className="text-center py-8 text-zinc-600 text-sm">
                    <p>No checklist items yet</p>
                    <p className="text-xs mt-1">Generate smart items or add your own below</p>
                  </div>
                ) : (
                  checklistItems.map(item => (
                    <div
                      key={item.id}
                      className="flex items-start gap-3 p-3 rounded-lg bg-zinc-900/40 border border-zinc-800 group"
                    >
                      <Checkbox
                        checked={item.completed}
                        onChange={() => handleToggleChecklistItem(item.id)}
                      />
                      <div className="flex-1">
                        <p className={cn('text-sm', item.completed ? 'text-zinc-500 line-through' : 'text-zinc-200')}>
                          {item.text}
                        </p>
                        {item.isAutoGenerated && (
                          <span className="text-[10px] text-zinc-600">Auto-generated</span>
                        )}
                      </div>
                      {!item.isAutoGenerated && (
                        <button
                          onClick={() => handleRemoveChecklistItem(item.id)}
                          className="opacity-0 group-hover:opacity-100 text-zinc-600 hover:text-red-400 transition-all"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      )}
                    </div>
                  ))
                )}
              </div>

              {/* Add new item */}
              <div className="flex gap-2">
                <Input
                  placeholder="Add checklist item..."
                  value={newChecklistItem}
                  onChange={e => setNewChecklistItem(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && handleAddChecklistItem()}
                />
                <Button onClick={handleAddChecklistItem}>Add</Button>
              </div>

              {/* Verification status */}
              {totalChecklist > 0 && (
                <div className={cn(
                  'p-3 rounded-lg border',
                  completedChecklist === totalChecklist
                    ? 'bg-emerald-500/5 border-emerald-500/20'
                    : 'bg-zinc-900/40 border-zinc-800'
                )}>
                  <div className="flex items-center gap-2">
                    {completedChecklist === totalChecklist ? (
                      <>
                        <span className="text-emerald-400 text-lg">✅</span>
                        <div>
                          <p className="text-sm font-semibold text-emerald-400">Verified Complete</p>
                          <p className="text-xs text-zinc-500">All checklist items completed</p>
                        </div>
                      </>
                    ) : (
                      <>
                        <span className="text-blue-400 text-lg">📋</span>
                        <div>
                          <p className="text-sm font-semibold text-zinc-300">{completedChecklist} of {totalChecklist} completed</p>
                          <p className="text-xs text-zinc-500">Complete all items for verification</p>
                        </div>
                      </>
                    )}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* DOCUMENTS TAB */}
          {activeTab === 'documents' && (
            <div className="space-y-6">
              {/* Suggested documents */}
              {suggestedDocs.length > 0 && (
                <div>
                  <h3 className="text-sm font-semibold text-zinc-300 mb-3">Suggested Documents</h3>
                  <div className="space-y-2">
                    {suggestedDocs.map(doc => {
                      const docData = documentationData.find(d => d.id === doc.id);
                      const isLinked = linkedDocuments.includes(doc.id);
                      
                      if (!docData) return null;

                      return (
                        <div
                          key={doc.id}
                          className="flex items-center justify-between p-3 rounded-lg bg-zinc-900/40 border border-zinc-800 hover:border-zinc-700 transition-colors"
                        >
                          <div className="flex-1 min-w-0">
                            <p className="text-sm text-zinc-200 truncate">{doc.name}</p>
                            <p className="text-xs text-zinc-600">{docData.type}</p>
                          </div>
                          <Button
                            size="sm"
                            variant={isLinked ? 'ghost' : 'secondary'}
                            onClick={() => handleLinkDocument(doc.id)}
                            disabled={isLinked}
                          >
                            {isLinked ? '✓ Linked' : 'Link'}
                          </Button>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Linked documents */}
              {linkedDocuments.length > 0 && (
                <div>
                  <h3 className="text-sm font-semibold text-zinc-300 mb-3">Linked Documents</h3>
                  <div className="space-y-2">
                    {linkedDocuments.map(docId => {
                      const doc = documentationData.find(d => d.id === docId);
                      if (!doc) return null;

                      return (
                        <div
                          key={docId}
                          className="flex items-center justify-between p-3 rounded-lg bg-blue-500/5 border border-blue-500/20 hover:border-blue-500/40 transition-colors group"
                        >
                          <Link href="/documents" className="flex-1 min-w-0">
                            <p className="text-sm text-zinc-200 group-hover:text-blue-400 transition-colors">{doc.artifact}</p>
                            <p className="text-xs text-zinc-600">{doc.type}</p>
                          </Link>
                          <button
                            onClick={() => handleUnlinkDocument(docId)}
                            className="ml-2 p-1.5 rounded hover:bg-red-500/10 text-zinc-600 hover:text-red-400 transition-colors"
                            title="Unlink document"
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                          </button>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Attached files */}
              {attachedFiles.length > 0 && (
                <div>
                  <h3 className="text-sm font-semibold text-zinc-300 mb-3">Attached Files</h3>
                  <div className="space-y-2">
                    {attachedFiles.map(file => (
                      <div
                        key={file.id}
                        className="flex items-center justify-between p-3 rounded-lg bg-zinc-900/40 border border-zinc-800"
                      >
                        <div className="flex-1">
                          <p className="text-sm text-zinc-200">{file.name}</p>
                          <p className="text-xs text-zinc-600">{(file.size / 1024).toFixed(1)} KB</p>
                        </div>
                        <button className="text-zinc-600 hover:text-red-400 transition-colors">
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Empty state */}
              {suggestedDocs.length === 0 && linkedDocuments.length === 0 && attachedFiles.length === 0 && (
                <div className="text-center py-8 text-zinc-600 text-sm">
                  <p>No related documents yet</p>
                  <p className="text-xs mt-1">Link documents or attach files to this task</p>
                </div>
              )}

              {/* Actions */}
              <div className="flex gap-2">
                <Button variant="secondary" className="flex-1">
                  <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
                  </svg>
                  Attach File
                </Button>
                <Button variant="secondary" className="flex-1">
                  <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
                  </svg>
                  Link Document
                </Button>
              </div>
            </div>
          )}

          {/* ACTIVITY HISTORY TAB */}
          {activeTab === 'history' && (
            <div>
              <h3 className="text-sm font-semibold text-zinc-300 mb-4">Activity Timeline</h3>
              
              {activityLog.length === 0 ? (
                <div className="text-center py-8 text-zinc-600 text-sm">
                  <p>No activity recorded yet</p>
                  <p className="text-xs mt-1">Changes will be logged automatically</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {activityLog.map(entry => (
                    <div key={entry.id} className="flex gap-3">
                      <div className="w-2 h-2 rounded-full bg-blue-500 mt-1.5 shrink-0" />
                      <div className="flex-1">
                        <p className="text-sm text-zinc-200">{entry.action}</p>
                        {entry.details && (
                          <p className="text-xs text-zinc-600 mt-0.5">{entry.details}</p>
                        )}
                        <p className="text-xs text-zinc-700 mt-1">
                          {new Date(entry.timestamp).toLocaleString()}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* NOTES SECTION (always visible at bottom) */}
          <div className="border-t border-zinc-800 pt-6">
            <h3 className="text-sm font-semibold text-zinc-300 mb-3">Notes</h3>
            <textarea
              className="w-full px-3 py-2 rounded-lg bg-zinc-900 border border-zinc-800 text-sm text-zinc-200 placeholder-zinc-600 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              rows={4}
              placeholder="Add notes or context for this task (markdown supported)..."
              value={noteText || meta.note || ''}
              onChange={e => setNoteText(e.target.value)}
            />
            {task.description && (
              <div className="mt-3 p-3 rounded-lg bg-zinc-900/40 border border-zinc-800">
                <p className="text-xs text-zinc-500 mb-1 font-semibold uppercase tracking-wider">Description</p>
                <p className="text-sm text-zinc-300">{task.description}</p>
              </div>
            )}
          </div>

          {/* ACTION BUTTONS */}
          <div className="flex gap-2 sticky bottom-0 bg-zinc-950 py-4 border-t border-zinc-800 -mx-4 px-4">
            <Button variant="secondary" onClick={handleSaveNote} className="flex-1">
              Save Notes
            </Button>
            <Button
              variant={isCompleted ? 'ghost' : 'primary'}
              onClick={handleMarkComplete}
              className="flex-1"
            >
              {isCompleted ? 'Mark Incomplete' : 'Mark Complete'}
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}
